# Generated by Django 5.1.1 on 2024-10-04 08:08

from django.db import migrations

def assign_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    
    # Define roles and their respective permissions
    permissions = {
        'student': [],
        'staff': ['can_view_students', 'can_view_hod'],
        'hod': ['can_view_students', 'can_manage_staff'],
    }
    
    for role, perms in permissions.items():
        for perm in perms:
            permission = Permission.objects.get(codename=perm)
            role_instance = apps.get_model('users', 'CustomUser').objects.get(role=role)
            role_instance.user_permissions.add(permission)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.RunPython(assign_permissions),
    ]
