# Generated by Django 5.1.1 on 2024-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_section_year_alter_customuser_section_section_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
