# Generated by Django 5.1.1 on 2024-10-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
