# Generated by Django 5.1.1 on 2024-10-03 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmarks',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to=settings.AUTH_USER_MODEL),
        ),
    ]
